# Use an official Node.js runtime as a base image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the app's port (use the correct port your Socket.IO server listens on)
EXPOSE 4000

# Start the application (change this to app.js)
CMD ["node", "app.js"]
